# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from simulation import simulation_pb2 as simulation_dot_simulation__pb2


class SimulationStub(object):
  """Input forces from OSP, step Unity the duration of "stepSize", return position and velocity
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoStep = channel.unary_unary(
        '/simulation.Simulation/DoStep',
        request_serializer=simulation_dot_simulation__pb2.StepRequest.SerializeToString,
        response_deserializer=simulation_dot_simulation__pb2.StepResponse.FromString,
        )
    self.Reset = channel.unary_unary(
        '/simulation.Simulation/Reset',
        request_serializer=simulation_dot_simulation__pb2.ResetRequest.SerializeToString,
        response_deserializer=simulation_dot_simulation__pb2.ResetResponse.FromString,
        )


class SimulationServicer(object):
  """Input forces from OSP, step Unity the duration of "stepSize", return position and velocity
  """

  def DoStep(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    """Reset the position and velocity of a vessel to the specified values
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoStep': grpc.unary_unary_rpc_method_handler(
          servicer.DoStep,
          request_deserializer=simulation_dot_simulation__pb2.StepRequest.FromString,
          response_serializer=simulation_dot_simulation__pb2.StepResponse.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=simulation_dot_simulation__pb2.ResetRequest.FromString,
          response_serializer=simulation_dot_simulation__pb2.ResetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'simulation.Simulation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
