// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: force/force.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Force {
  public static partial class Force
  {
    static readonly string __ServiceName = "force.Force";

    static readonly grpc::Marshaller<global::Force.ForceRequest> __Marshaller_force_ForceRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Force.ForceRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Force.ForceResponse> __Marshaller_force_ForceResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Force.ForceResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Force.ForceRequest, global::Force.ForceResponse> __Method_ApplyForce = new grpc::Method<global::Force.ForceRequest, global::Force.ForceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ApplyForce",
        __Marshaller_force_ForceRequest,
        __Marshaller_force_ForceResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Force.ForceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Force</summary>
    [grpc::BindServiceMethod(typeof(Force), "BindService")]
    public abstract partial class ForceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Force.ForceResponse> ApplyForce(global::Force.ForceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Force</summary>
    public partial class ForceClient : grpc::ClientBase<ForceClient>
    {
      /// <summary>Creates a new client for Force</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ForceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Force that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ForceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ForceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ForceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Force.ForceResponse ApplyForce(global::Force.ForceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ApplyForce(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Force.ForceResponse ApplyForce(global::Force.ForceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ApplyForce, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Force.ForceResponse> ApplyForceAsync(global::Force.ForceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ApplyForceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Force.ForceResponse> ApplyForceAsync(global::Force.ForceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ApplyForce, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ForceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ForceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ForceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ApplyForce, serviceImpl.ApplyForce).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ForceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ApplyForce, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Force.ForceRequest, global::Force.ForceResponse>(serviceImpl.ApplyForce));
    }

  }
}
#endregion
