# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from force import force_pb2 as force_dot_force__pb2


class ForceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ApplyForce = channel.unary_unary(
        '/force.Force/ApplyForce',
        request_serializer=force_dot_force__pb2.ForceRequest.SerializeToString,
        response_deserializer=force_dot_force__pb2.ForceResponse.FromString,
        )


class ForceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ApplyForce(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ForceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ApplyForce': grpc.unary_unary_rpc_method_handler(
          servicer.ApplyForce,
          request_deserializer=force_dot_force__pb2.ForceRequest.FromString,
          response_serializer=force_dot_force__pb2.ForceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'force.Force', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
