# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensordata/sensordata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensordata/sensordata.proto',
  package='sensordata',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.sensordataB\nSensordataP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x1bsensordata/sensordata.proto\x12\nsensordata\"&\n\x11SensordataRequest\x12\x11\n\toperation\x18\x01 \x01(\t\"6\n\x12SensordataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\ndataLength\x18\x02 \x01(\x05\x32\xba\x01\n\nSensordata\x12U\n\x12TransferSensordata\x12\x1d.sensordata.SensordataRequest\x1a\x1e.sensordata.SensordataResponse\"\x00\x12U\n\x10StreamSensordata\x12\x1d.sensordata.SensordataRequest\x1a\x1e.sensordata.SensordataResponse\"\x00\x30\x01\x42\x31\n\x1bio.grpc.examples.sensordataB\nSensordataP\x01\xa2\x02\x03HLWb\x06proto3')
)




_SENSORDATAREQUEST = _descriptor.Descriptor(
  name='SensordataRequest',
  full_name='sensordata.SensordataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='sensordata.SensordataRequest.operation', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=81,
)


_SENSORDATARESPONSE = _descriptor.Descriptor(
  name='SensordataResponse',
  full_name='sensordata.SensordataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='sensordata.SensordataResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataLength', full_name='sensordata.SensordataResponse.dataLength', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['SensordataRequest'] = _SENSORDATAREQUEST
DESCRIPTOR.message_types_by_name['SensordataResponse'] = _SENSORDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensordataRequest = _reflection.GeneratedProtocolMessageType('SensordataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATAREQUEST,
  '__module__' : 'sensordata.sensordata_pb2'
  # @@protoc_insertion_point(class_scope:sensordata.SensordataRequest)
  })
_sym_db.RegisterMessage(SensordataRequest)

SensordataResponse = _reflection.GeneratedProtocolMessageType('SensordataResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATARESPONSE,
  '__module__' : 'sensordata.sensordata_pb2'
  # @@protoc_insertion_point(class_scope:sensordata.SensordataResponse)
  })
_sym_db.RegisterMessage(SensordataResponse)


DESCRIPTOR._options = None

_SENSORDATA = _descriptor.ServiceDescriptor(
  name='Sensordata',
  full_name='sensordata.Sensordata',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='TransferSensordata',
    full_name='sensordata.Sensordata.TransferSensordata',
    index=0,
    containing_service=None,
    input_type=_SENSORDATAREQUEST,
    output_type=_SENSORDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamSensordata',
    full_name='sensordata.Sensordata.StreamSensordata',
    index=1,
    containing_service=None,
    input_type=_SENSORDATAREQUEST,
    output_type=_SENSORDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORDATA)

DESCRIPTOR.services_by_name['Sensordata'] = _SENSORDATA

# @@protoc_insertion_point(module_scope)
