// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cameradata/cameradata.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cameradata {
  /// <summary>
  /// The data service definition
  /// </summary>
  public static partial class CameradataService
  {
    static readonly string __ServiceName = "cameradata.CameradataService";

    static readonly grpc::Marshaller<global::Cameradata.CameradataRequest> __Marshaller_cameradata_CameradataRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cameradata.CameradataRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cameradata.CameradataResponse> __Marshaller_cameradata_CameradataResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cameradata.CameradataResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse> __Method_TransferImagedata = new grpc::Method<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferImagedata",
        __Marshaller_cameradata_CameradataRequest,
        __Marshaller_cameradata_CameradataResponse);

    static readonly grpc::Method<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse> __Method_StreamImagedata = new grpc::Method<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamImagedata",
        __Marshaller_cameradata_CameradataRequest,
        __Marshaller_cameradata_CameradataResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cameradata.CameradataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CameradataService</summary>
    [grpc::BindServiceMethod(typeof(CameradataService), "BindService")]
    public abstract partial class CameradataServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Cameradata.CameradataResponse> TransferImagedata(global::Cameradata.CameradataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StreamImagedata(global::Cameradata.CameradataRequest request, grpc::IServerStreamWriter<global::Cameradata.CameradataResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CameradataService</summary>
    public partial class CameradataServiceClient : grpc::ClientBase<CameradataServiceClient>
    {
      /// <summary>Creates a new client for CameradataService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CameradataServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CameradataService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CameradataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CameradataServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CameradataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Cameradata.CameradataResponse TransferImagedata(global::Cameradata.CameradataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransferImagedata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Cameradata.CameradataResponse TransferImagedata(global::Cameradata.CameradataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransferImagedata, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Cameradata.CameradataResponse> TransferImagedataAsync(global::Cameradata.CameradataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TransferImagedataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Cameradata.CameradataResponse> TransferImagedataAsync(global::Cameradata.CameradataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransferImagedata, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Cameradata.CameradataResponse> StreamImagedata(global::Cameradata.CameradataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamImagedata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Cameradata.CameradataResponse> StreamImagedata(global::Cameradata.CameradataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamImagedata, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CameradataServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CameradataServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CameradataServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TransferImagedata, serviceImpl.TransferImagedata)
          .AddMethod(__Method_StreamImagedata, serviceImpl.StreamImagedata).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CameradataServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_TransferImagedata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse>(serviceImpl.TransferImagedata));
      serviceBinder.AddMethod(__Method_StreamImagedata, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Cameradata.CameradataRequest, global::Cameradata.CameradataResponse>(serviceImpl.StreamImagedata));
    }

  }
}
#endregion
