name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build my project
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'feature/testing'

      # Cache
      #- uses: actions/cache@v2
      #  with:
      #    path: Gemini-Unity/Library
      #    key: Library

      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v2
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    githubtoken: ${{ secrets.GEMINI_CI_TOKEN }}

      # Run Setup Powershell script
      - name: Setup shell
        run: .\setup.ps1

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.4.20f1
          projectPath: Gemini-Unity
          targetPlatform: StandaloneWindows64

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Gemini-Unity/build